server:
   port: 8100

#zuul.routes.Admin-Service.url= http://localhost:8081/admin/home
#zuul.routes.Coupon-Service.url= http://localhost:8082/coupon/home
#zuul.routes.User-Service.url= http://localhost:8083/user/home

#spring.cloud.gateway.routes.url=http://localhost:8081/admin/home

spring:
  cloud:
    gateway:
      routes:
      - id: Admin-Service
        uri: http://localhost:8081/
        predicates:
        - Path=/admin/**
        
      - id: Coupon-Service
        uri: http://localhost:8082/
        predicates:
        - Path=/coupon/**
       
      - id: User-Service
        uri: http://localhost:8083/
        predicates:
        - Path=/user/**